### ISSUE TITLE
用这个库算SM9对运算，比GMP库慢一倍，GMP比openssl又慢一倍。。。

### ISSUE THREAD

**Issue by zweib730** [piggypiggy/fp256#3]

**Comment by piggypiggy** [comment]
我需要具体的配置信息才能判断原因，包括系统、CPU、编译参数等。
`cmake ..` 会显示这些信息。

正常情况下，应该是fp256比gmp快一点，gmp比openssl快很多。用fp256和gmp实现的sm9双线性对运算的时间应该稍小于 1ms，也就是稍大于 1000 次/s。

**Comment by piggypiggy** [comment]
当然这还和你的双线性对实现有关。
